---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: '11.14.6'
  use_vagrant_berkshelf_plugin: true
provisioner:
  name: chef_zero
  client_rb:
    node_name: walle

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04

suites:
- name: default
  run_list: ["recipe[martinisoft-server]"]
  data_bags_path: test/integration/data_bags
  attributes:
    openssh:
      internal_only: false
      server:
        port: [ '22', '22022' ]
- name: digitalocean
  run_list: ["recipe[martinisoft-server]"]
  data_bags_path: test/integration/data_bags
  attributes:
    tags: [ 'digitalocean' ]
    openssh:
      internal_only: false
      server:
        port: [ '22', '22022' ]
