---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: '11.12.4'
  use_vagrant_berkshelf_plugin: true

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list: ["recipe[martinisoft-server]"]
  attributes: {}
