---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: '11.14.6'
  solo_rb:
    node_name: walle

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04

suites:
- name: default
  run_list: ["recipe[martinisoft-server]"]
  attributes:
- name: users
  run_list: ["recipe[martinisoft-server]"]
  data_bags_path: test/integration/data_bags/
  attributes:
- name: digitalocean
  run_list: ["recipe[martinisoft-server]"]
  attributes:
    tags: [ 'digitalocean' ]
