---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: '11.12.4'
  use_vagrant_berkshelf_plugin: true
provisioner: chef_zero

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04

suites:
- name: default
  run_list: ["recipe[martinisoft-server]"]
  data_bags_path: test/integration/default/data_bags
  attributes:
    openssh:
      internal_only: false
      server:
        port: [ '22', '22022' ]
